/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // Ver docs/03-conventions.md §6
    'scope-enum': [
      2,
      'always',
      [
        'web',
        'admin',
        'api',
        'workers',
        'mobile',
        'ui',
        'tokens',
        'contracts',
        'domain',
        'sdk',
        'auth',
        'i18n',
        'analytics',
        'observability',
        'testing',
        'utils',
        'config',
        'identity',
        'accounts',
        'catalog',
        'pricing',
        'cart',
        'checkout',
        'orders',
        'content',
        'notifications',
        'search',
        'infra',
        'docs',
        'deps',
        'e2e',
      ],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'body-max-line-length': [1, 'always', 100],
  },
}
